### PR TITLE
[Feature] authentication for `get_blocks` and `get_delegators` endpoints

### PR DESCRIPTION
**Pull request by niklaslong**
These requests can return large responses and be expensive to compute so it was suggested we move these behind authentication as an extra precaution in addition to rate-limiting.

### CODE REVIEW

**Review by vicsn — APPROVED** [review]

**Comment by howardwu** [comment]
While this PR is technically sound, I strongly advise an approval from Jake, as this will clearly break the Explorer.

Please hold and await confirmation prior to this PR being merged.

Alternatively, a CLI toggle such as `--no-rest-safety` may be introduced to selectively toggle the auth guard on these endpoints.

**Comment by vicsn** [comment]
Can't add you as reviewer so doing it manually CC @jaketarnow

**Review by jaketarnow — COMMENTED** [review]
Thank you for the ping on this PR. I would like to hold on merging this until I have a convo with @niklaslong to get more background into the motivation behind this and testing of it.

**Comment by niklaslong** [comment]
Moved to AleoNet.

**Pull request closed without merging**
